In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import scipy
from scipy import stats

### Question 1
We're going to briefly look at truth tables. As an example let's assume we have a 100 photos, some of birds and some of people. In a truth table you assume you can categorize the true answer—let's say you pay an undergraduate to sort the photos into birds and people. Then you want to have an automated sorting algorithm. However that works, whether it is by looking a the color at the center of photo or using a neural network (NN) or an AI agent, it will also sort the photos but imperfectly. Given two sorts you can then arrange a truth table:

In [2]:
data_NN = {
    " ": ["NN Bird", "NN Person"],
    "True Bird": [45, 3],
    "True Person": [5, 47]
}

df_NN = pd.DataFrame(data_NN)
df_NN

              True Bird  True Person
0    NN Bird         45            5
1  NN Person          3           47

There are 48 birds and 52 People (columns), and there are 8 miscategorizations. The AI called three of the birds people, and 5 of the people birds.

This is useful because it not only shows the number of errors, but the type, and not all errors are created equal. Let's say our identification system is being used to keep birds from escaping the aviary at the zoo by locking the aviary door when a bird is trying to escape. We really don't want to let birds escape, but locking a person in for 30 extra seconds is not a big deal. In this case false bird identification is not so bad, but false person identification lets a bird escape.

Let's say the above truth table is the current system, and you've developed a new algorithm (NA) with the following truth table:

In [3]:
data_NA = {
    " ": ["N Bird", "NA Person"],
    "True Bird": [47, 1],
    "True Person": [11, 42]
}

df_NA = pd.DataFrame(data_NA)
df_NA

              True Bird  True Person
0     N Bird         47           11
1  NA Person          1           42

#### Part (a)
Which algorithm makes the fewest mistakes?

The first (NN) algorithm makes fewer mistakes (8 mistakes) compared to the second algorithm (NA) (11 mistakes).

#### Part (b)
Which algorithm is better for the zoo? Explain.

The second algorithm is better for the zoo as it misidentifies birds for people only one time while the first algorithm misidentifies birds for people three times out of the same sample. As stated above, misidentifying birds for people matters more than other errors as that's what allows the bird to escape. While there are more errors in the second algorithm, it makes less consequential mistakes.

#### Part (c)
During the pandemic the number of visitors plummets, and it is only the zoo keeper visiting. So instead of 52% of the photos taken at the aviary door being people, it is now only 1%. Make new truth tables for both algorithms.

In [4]:
N_person = 1
N_bird = 99

NN_bird_true = 45/48
NN_person_false = 3/48
NN_bird_false = 5/52
NN_person_true = 47/52

data_NN_1 = {
    " ": ["NN Bird", "NN Person"],
    "True Bird": [NN_bird_true * N_bird, NN_person_false * N_bird],
    "True Person": [NN_bird_false * N_person, NN_person_true * N_person]
}

df_NN_1 = pd.DataFrame(data_NN_1)
df_NN_1

              True Bird  True Person
0    NN Bird    92.8125     0.096154
1  NN Person     6.1875     0.903846

In [5]:
NA_bird_true = 47/48
NA_person_false = 1/48
NA_bird_false = 11/52
NA_person_true = 42/52

data_NA_1 = {
    " ": ["NA Bird", "NA Person"],
    "True Bird": [NA_bird_true * N_bird, NA_person_false * N_bird],
    "True Person": [NA_bird_false * N_person, NA_person_true * N_person]
}

df_NA_1 = pd.DataFrame(data_NA_1)
df_NA_1

              True Bird  True Person
0    NA Bird    96.9375     0.211538
1  NA Person     2.0625     0.807692

### Problem 2
In the last lab we explored how to numerically calculate the pdf of a summed or averaged observation through repeated convolutions. But sometimes the convolution has an analytical solution. We could have found this out by either using a sharp pencil and doing the convolution integral by hand, or by looking it up in a table (much easier).

Having an analytic answer is much nicer when they exist, so it is always good to look and see if it exists. Further, sums and averages are only some of the mathematical operations that we can perform. In this section we will do an internet scavenger hunt to find the analytic pdf for some interesting distributions.

#### Part (a)
What is the pdf of the sum of two identical exponential distributions?

$ \Large f_Z(z)$ 

$ \Large = \int_{-\infty}^{\infty} f_{X_1}(x_1)f_{X_2}(z-x_1)dx_1$

$ \Large = \int_0^z \lambda_1 e^{-\lambda_1 x_1} \lambda_2 e^{-\lambda_2(z-x_1)}dx_1$

$ \Large = \lambda_1 \lambda_2 e^{-\lambda_2z}\int_0^z e^{(\lambda_2 - \lambda_1)x_1} dx_1 $

$ \Large = \lambda^2 z e^{-\lambda z} $ where $\lambda = \lambda_1 = \lambda_2 $

(From Wikipedia: Exponential Distribution - Sum of two independent exponential random variables)

#### Part (b)
What is the pdf of the ratio of two zero-mean unity variance normal distributions $X_1/X_2$

If $X_1$ and $X_2$ are two zero-mean unity variance normal distributions ($X \sim N(0,1)$), then their ratio, $X_1 / X_2$, follows a standard Cauchy distribution ($X_1 / X_2 \sim Cauchy(0, 1)$)

(From Wikipedia: Normal Distribution - Operations on two independent standard normal variables)

#### Part (c)
So far we have looked at 1D probability distributions, but it is possible to have a multi-dimensional vector distribution. A simple first introduction is the 2D Gaussian; it looks like a smeared spot. Mathematically this is given by $X + iY$ where both $X$ and $Y$ are drawn from 1D Gaussian distributions. If I measure the amplitude of this vector, what is its pdf? (Hint, the amplitude is always positive.)

Assuming the Gaussian distributions are centered and IID, the amplitude of the vector $X+iY$ follows a Rayleigh distribution ($R \sim Rayleigh(\sigma)$ where $R = \sqrt{X^2 + Y^2}$ and $X, Y \sim N(0, \sigma^2)$

(From Wikipedia: Rayleigh distribution - Related distributions and also a statistican)


Note: This is derived from joint pdf of X and Y by changing to polar coordinates